import os
import base64
import io
from PIL import Image
from flask import Flask, request, jsonify
from flask_cors import CORS
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)
CORS(app) # Allow cross-origin requests from the frontend

# Configure Gemini API
genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
# Using the newer 2.5 flash model as requested
model = genai.GenerativeModel('gemini-2.5-flash')

@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Get the user's drawing from the request
        drawing_b64 = request.json['drawing']
        
        # Remove the base64 header if present (e.g. data:image/png;base64,)
        if ',' in drawing_b64:
            drawing_b64 = drawing_b64.split(',')[1]
            
        # Convert the base64 string to a PIL image
        image_data = base64.b64decode(drawing_b64)
        image = Image.open(io.BytesIO(image_data)).convert('RGB')

        # Create a prompt for Gemini
        prompt = "You are an AI assistant analyzing a user's sketch. Describe what the user drew in a fun, creative way. If it's ambiguous, take a playful guess!"

        # Call Gemini API
        response = model.generate_content([prompt, image])

        # Return the text generated by Gemini
        return jsonify({'result': 'success', 'text': response.text})

    except Exception as e:
        print(f"Error: {e}")
        return jsonify({'result': 'error', 'message': str(e)}), 500


if __name__ == '__main__':
    app.run(debug=True)

# Path: frontend\src\App.js

